### ISSUE TITLE
Orchestrator crashes when Evaluator is FINISHED_WITH_ISSUES

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#1017]
All of our ORT runs are failing in Evaluator phase. Here's the relevant part of stack trace from Orchestrator:
```
2024-09-11 12:16:04.850 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.orchestrator.Orchestrator - Handling a completed job for endpoint 'scanner' and ORT run 158.
	
2024-09-11 12:16:04.885 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.transport.MessagePublisher - Sending 'EvaluatorRequest' message to 'EvaluatorEndpoint'. TraceID: '84402bf4-6ad6-4dee-a236-77563cb4e72d'.
	
2024-09-11 12:16:04.885 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.t.MessageSenderFactory - Creating a MessageSender of type 'rabbitMQ' for endpoint 'evaluator'.
	
2024-09-11 12:16:04.886 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - Creating RabbitMQ sender for endpoint 'evaluator'.
	
2024-09-11 12:16:04.886 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ server URI: 'amqp://rabbitmq:5672'
	
2024-09-11 12:16:04.886 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ user: 'admin'
	
2024-09-11 12:16:04.886 [pool-2-thread-8] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ queue: 'evaluator_queue'
	
2024-09-11 12:18:01.185 [pool-2-thread-9] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.orchestrator.EntrypointKt - Received 'EvaluatorWorkerResult' message. TraceID: '84402bf4-6ad6-4dee-a236-77563cb4e72d'.
	
2024-09-11 12:18:01.185 [pool-2-thread-9] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=INFO  o.e.a.o.orchestrator.Orchestrator - Job 23 for endpoint 'evaluator' completed in status 'FINISHED_WITH_ISSUES'.
	
2024-09-11 12:18:01.193 [pool-2-thread-9] [traceId=84402bf4-6ad6-4dee-a236-77563cb4e72d, ortRunId=158, component=orchestrator] level=WARN  o.e.a.o.orchestrator.Orchestrator - Failed to handle 'EvaluatorWorkerResult' message.
	at org.eclipse.apoapsis.ortserver.model.repositories.WorkerJobRepository$DefaultImpls.complete(WorkerJobRepository.kt:74)
		java.lang.IllegalArgumentException: complete can only be called with a JobStatus that mark the job as completed: [FINISHED, FAILED].
	at org.eclipse.apoapsis.ortserver.orchestrator.WorkerJobRepositories.updateJobStatus(WorkerJobRepositories.kt:97)
	at org.eclipse.apoapsis.ortserver.model.repositories.EvaluatorJobRepository$DefaultImpls.complete(EvaluatorJobRepository.kt:28)
	at org.eclipse.apoapsis.ortserver.dao.repositories.DaoEvaluatorJobRepository.complete(DaoEvaluatorJobRepository.kt:39)
	at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.handleCompletedJob$lambda$17(Orchestrator.kt:316)
	at org.eclipse.apoapsis.ortserver.orchestrator.WorkerJobRepositories.updateJobStatus$default(WorkerJobRepositories.kt:90)
	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt.blockingQueryCatching$lambda$11$lambda$10(Database.kt:165)
	...
	at java.base/java.lang.Thread.run(Thread.java:840)
```

I guess from the log it can be seen that this points out to #945, as the Orchestrator cannot seem to handle the new `FINISHED_WITH_ISSUES` state properly? In Docker Compose environment, this leaves the run hanging on Evaluator for an hour or more. In our deployment environment, the run finally was declared FAILED, after roughly an hour.

Seems like [completedJobStates](https://github.com/eclipse-apoapsis/ort-server/blob/b8df68b3da5fdf51243c57a482ec5d391a5655eb/model/src/commonMain/kotlin/repositories/WorkerJobRepository.kt#L111) is missing the new state...

**Comment by sschuberth** [comment]
Any idea @nnobelis?

**Comment by nnobelis** [comment]
I will prepare a PR.

It's a bit messy to have this extra collection as there is already a Worker extension function for it:
https://github.com/eclipse-apoapsis/ort-server/blob/34b4f82afa06ed7922c51645bd07b1ad2508c6dd/orchestrator/src/main/kotlin/WorkerScheduleContext.kt#L115

**Comment by Etsija** [comment]
Evaluator is still failing for all runs - now "gracefully", without waiting an hour, but immediately after the job is finished - with an error message that again points to state handling:
```
2024-09-12 07:55:39.636	2024-09-12 04:55:39.634 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ queue: 'orchestrator_queue'
2024-09-12 07:55:39.635	2024-09-12 04:55:39.634 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ user: 'admin'
2024-09-12 07:55:39.635	2024-09-12 04:55:39.634 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ server URI: 'amqp://rabbitmq:5672'
2024-09-12 07:55:39.634	2024-09-12 04:55:39.634 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - Creating RabbitMQ sender for endpoint 'orchestrator'.
2024-09-12 07:55:39.628	2024-09-12 04:55:39.626 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.t.MessageSenderFactory - Creating a MessageSender of type 'rabbitMQ' for endpoint 'orchestrator'.
2024-09-12 07:55:39.628	2024-09-12 04:55:39.624 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=INFO  o.e.a.o.transport.MessagePublisher - Sending 'EvaluatorWorkerError' message to 'OrchestratorEndpoint'. TraceID: 'b4f76088-6a12-4e25-913a-db401a7d3381'.
2024-09-12 07:55:39.627		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
2024-09-12 07:55:39.627		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
2024-09-12 07:55:39.627		at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
2024-09-12 07:55:39.625		at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
2024-09-12 07:55:39.625		at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-09-12 07:55:39.625		at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
2024-09-12 07:55:39.625		at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
2024-09-12 07:55:39.624		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:839)
2024-09-12 07:55:39.624		at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:97)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:867)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport$ChildCompletion.invoke(JobSupport.kt:1166)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:294)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:317)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.continueCompleting(JobSupport.kt:947)
2024-09-12 07:55:39.624		at kotlinx.coroutines.JobSupport.access$continueCompleting(JobSupport.kt:22)
2024-09-12 07:55:39.622		at kotlinx.coroutines.DispatchedCoroutine.afterCompletion(Builders.common.kt:251)
2024-09-12 07:55:39.622		at kotlinx.coroutines.DispatchedCoroutine.afterResume(Builders.common.kt:257)
2024-09-12 07:55:39.621		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith$default(DispatchedContinuation.kt:274)
2024-09-12 07:55:39.621		at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:279)
2024-09-12 07:55:39.620		at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-09-12 07:55:39.620		at org.eclipse.apoapsis.ortserver.workers.evaluator.EvaluatorRunner$run$1.invokeSuspend(EvaluatorRunner.kt)
2024-09-12 07:55:39.620		at org.eclipse.apoapsis.ortserver.workers.evaluator.EvaluatorRunner.run(EvaluatorRunner.kt:103)
2024-09-12 07:55:39.620		at org.ossreviewtoolkit.plugins.packageconfigurationproviders.api.PackageConfigurationProviderFactory$Companion.create(PackageConfigurationProviderFactory.kt:52)
2024-09-12 07:55:39.619		at org.ossreviewtoolkit.plugins.packageconfigurationproviders.dos.DosPackageConfigurationProviderFactory.create(DosPackageConfigurationProviderFactory.kt:15)
2024-09-12 07:55:39.619		at org.ossreviewtoolkit.plugins.packageconfigurationproviders.dos.DosPackageConfigurationProviderFactory.create(DosPackageConfigurationProviderFactory.kt:9)
2024-09-12 07:55:39.618	2024-09-12 04:55:39.615 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=ERROR o.e.a.o.w.e.EvaluatorComponent - Evaluator job '24' failed.
2024-09-12 07:55:39.618	java.lang.IllegalStateException: Option token is required but not set.
2024-09-12 07:55:39.612	2024-09-12 04:55:39.613 [DefaultDispatcher-worker-1] [traceId=b4f76088-6a12-4e25-913a-db401a7d3381, ortRunId=159, component=evaluator-worker, evaluatorJobId=24] level=ERROR o.e.a.o.w.evaluator.EvaluatorWorker - Error while processing message with traceId 'b4f76088-6a12-4e25-913a-db401a7d3381': Option token is required but not set.

```

**Comment by sschuberth** [comment]
@Etsija please don't hijack issues this way, by changing the title and referring to another stack trace. This should have been a new, separate issue.
