### ISSUE TITLE
pnpm not there in node image and failing to build buildUIImage gradlew configuration

### ISSUE THREAD

**Issue by dineshr93** [eclipse-apoapsis/ort-server#1413]
commit: d52f27f9

Hello there, I tried to build the docker image locally in my wsl machine with Ubuntu 22.04 with gradle 8.11
<details>

<summary> docker version </summary>

```js
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

I doubt if there there is pnpn binary exported properly in the env I witnessed this error at https://github.com/eclipse-apoapsis/ort-server/blob/9a963342410236a8dcf137c4070f5c9b13210f84/ui/docker/UI.Dockerfile#L37
`./gradlew buildUIImage --parallel
`
![image](https://github.com/user-attachments/assets/7a1da7a9-1f90-4003-9c73-985e27721dde)

<details>

<summary>Full error</summary>

```js
   > ./gradlew --parallel buildUIImage
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
Daemon JVM discovery is an incubating feature.
Calculating task graph as configuration cache cannot be reused because the file system entry '.gradle/configuration-cache/2aihtipofxc76wdju3akc6qlp/buildfingerprint2467664718838631716.tmp' has been removed.
Type-safe project accessors is an incubating feature.

> Configure project :
Building ORT Server version 0.1.0-RC4.033.sha.d52f27f.

> Task :buildUIImage FAILED
UI.Dockerfile:37
--------------------
  35 |         VITE_UI_URL="UI_URL_PLACEHOLDER"
  36 |
  37 | >>> RUN pnpm install --frozen-lockfile
  38 |     RUN pnpm run build
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pnpm install --frozen-lockfile" did not complete successfully: exit code: 1
[Incubating] Problems report is available at: file:///home/dinesh/ort-server/build/reports/problems/problems-report.htm

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildUIImage'.
> Process 'command 'docker'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.11/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 47s
102 actionable tasks: 1 executed, 101 up-to-date
Configuration cache entry stored.
```

</details>

<details>

<summary>Actual error inside container</summary>

```js
   > docker run -it node:22-slim@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0 bash
Unable to find image 'node:22-slim@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0' locally
docker.io/library/node@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0: Pulling from library/node
a480a496ba95: Already exists
e28f673e04b0: Already exists
c737a44a97c3: Already exists
9f58814a2227: Already exists
b658bf75a5fb: Already exists
Digest: sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0
Status: Downloaded newer image for node@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0
root@8f9eb4d286c0:/# ls -l /pnpm
ls: cannot access '/pnpm': No such file or directory
root@8f9eb4d286c0:/# export PNPM_HOME="/pnpm"
root@8f9eb4d286c0:/# export PATH="$PNPM_HOME:$PATH"
root@8f9eb4d286c0:/# echo $PATH
/pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@8f9eb4d286c0:/# corepack enable
root@8f9eb4d286c0:/# which corepack
/usr/local/bin/corepack
root@8f9eb4d286c0:/# pnpm
^C
root@8f9eb4d286c0:/# pnpm -h
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21609
    throw new Error(
          ^

Error: Error when performing the request to https://registry.npmjs.org/pnpm/latest; for troubleshooting help, see https://github.com/nodejs/corepack#troubleshooting
    at fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21609:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21623:20)
    ... 4 lines matching cause stack trace ...
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  [cause]: TypeError: fetch failed
      at node:internal/deps/undici/undici:13392:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async fetch (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21603:16)
      at async fetchAsJson (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21623:20)
      at async fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21550:20)
      at async fetchLatestStableVersion2 (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21672:14)
      at async Engine.getDefaultVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22292:23)
      at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22390:47)
      at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
    [cause]: ConnectTimeoutError: Connect Timeout Error (attempted address: registry.npmjs.org:443, timeout: 10000ms)
        at onConnectTimeout (node:internal/deps/undici/undici:2599:28)
        at Immediate._onImmediate (node:internal/deps/undici/undici:2583:11)
        at process.processImmediate (node:internal/timers:491:21) {
      code: 'UND_ERR_CONNECT_TIMEOUT'
    }
  }
}

Node.js v22.11.0
```

</details>
From inside container pnpm cant reach https://registry.npmjs.org/pnpm/latest

but I can able to reach from out side
![image](https://github.com/user-attachments/assets/08a61c37-e2c9-446e-a2f2-e232da0aef46)

**Comment by dineshr93** [comment]
Hi @mmurto  Thanks for your comment. I will try it. parallely I found that in my wsl I had to expose the container manually  via --dns flag after which pnpm works 

```
docker run --dns 8.8.8.8 -it node:22-slim@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0 bash

root@1c0ab89dc46e:/# export PNPM_HOME="/pnpm" && export PATH="$PNPM_HOME:$PATH" && corepack enable

root@1c0ab89dc46e:/# pnpm -h
! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.12.3.tgz
? Do you want to continue? [Y/n] y

Version 9.12.3 (compiled to binary; bundled Node.js v22.11.0)
Usage: pnpm [command] [flags]
       pnpm [ -h | --help | -v | --version ]
```

**Comment by mmurto** [comment]
> Hi @mmurto Thanks for your comment. I will try it. parallely I found that in my wsl I had to expose the container manually via `--dns` flag after which pnpm works
> 
> ```
> docker run --dns 8.8.8.8 -it node:22-slim@sha256:f73e9c70d4279d5e7b7cc1fe307c5de18b61089ffa2235230408dfb14e2f09a0 bash
> 
> root@1c0ab89dc46e:/# export PNPM_HOME="/pnpm" && export PATH="$PNPM_HOME:$PATH" && corepack enable
> 
> root@1c0ab89dc46e:/# pnpm -h
> ! Corepack is about to download https://registry.npmjs.org/pnpm/-/pnpm-9.12.3.tgz
> ? Do you want to continue? [Y/n] y
> 
> Version 9.12.3 (compiled to binary; bundled Node.js v22.11.0)
> Usage: pnpm [command] [flags]
>        pnpm [ -h | --help | -v | --version ]
> ```
> 
> #To set gloablly the dns for the docker
> 
> ```
> sudo vi /etc/docker/daemon.json
> 
> #Add the following JSON configuration
> {
>   "dns": ["8.8.8.8"]
> }
> # restart the Docker daemon to apply the changes
> sudo systemctl restart docker
> ```
> 
> After adding above config UI coantainer is successfully built !!

Great, good to hear you solved it!
