### ISSUE TITLE
Downloading logs fails in ORT Server

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#1662]
Yesterday, I downloaded logs from ORT runs just fine, but now I get an unknown error (500 response) from back-end for all download attempts. Downloading code has not been touched for a while now in UI. Anyone know of any recent PR which might have caused this?

(This fails both in local Compose environment and in our infra.)

![Screenshot from 2024-12-17 13-50-52](https://github.com/user-attachments/assets/fa3a7155-971e-40a1-b781-c2f636ea4737)

The request is failing also when tested with PostMan:

![Screenshot from 2024-12-17 14-10-09](https://github.com/user-attachments/assets/7ae3b9e4-10e1-428f-b76a-0d6b05db7335)

Looks like the Reporter log is failing.

**Comment by mnonnenmacher** [comment]
@Etsija Did you check the if the server logs contain more details about why the download is failing?

**Comment by Etsija** [comment]
This is what I was able to extract from core logs:

[Explore-logs-2024-12-18 07_52_58.txt](https://github.com/user-attachments/files/18175741/Explore-logs-2024-12-18.07_52_58.txt)

**Comment by Etsija** [comment]
I think this might be the interesting part:
```
2024-12-18 07:52:37.744		Caused by: java.util.concurrent.CancellationException: Parent job is Cancelling
2024-12-18 07:52:37.744			at kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1571)
2024-12-18 07:52:37.744			at io.ktor.client.engine.UtilsKt$attachToUserJob$cleanupHandler$1.invoke(Utils.kt:97)
2024-12-18 07:52:37.744			at kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1604)
2024-12-18 07:52:37.744			at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-12-18 07:52:37.744			at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:99)
2024-12-18 07:52:37.744			at org.eclipse.apoapsis.ortserver.logaccess.LogFileService.access$downloadLogFile(LogFileService.kt:51)
2024-12-18 07:52:37.744			at org.eclipse.apoapsis.ortserver.logaccess.LogFileService$downloadLogFile$1.invokeSuspend(LogFileService.kt)
2024-12-18 07:52:37.743			at org.eclipse.apoapsis.ortserver.logaccess.LogFileService.downloadLogFile(LogFileService.kt:175)
2024-12-18 07:52:37.740			at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
```

**Comment by Etsija** [comment]
The error message seems to come [from here](https://github.com/eclipse-apoapsis/ort-server/blob/8efcaeb3fe14b35690bf2d902d0a49abc981ddd0/logaccess/spi/src/main/kotlin/LogFileService.kt#L149-L178).

**Comment by sschuberth** [comment]
@mnonnenmacher, @oheger-bosch, could https://github.com/eclipse-apoapsis/ort-server/pull/1628 be in any way related?

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher, @oheger-bosch, could #1628 be in any way related?

I'm not sure how, it does not touch code related to log handling. But if you had stuck ORT runs they would be continued after applying that change, even if they were stuck for a very long time.

@Etsija Did the log download ever work in Compose? I have never tried it and am not sure if it was set up correctly.

**Comment by Etsija** [comment]
It has worked perfectly before, and on Monday 11:35 Finnish time it also worked on our infra, but not since.

**Comment by sschuberth** [comment]
@mnonnenmacher can you actually reproduce the issue on your infrastructure? Because like @Etsija said, this is not limited to the Compose setup for us.

**Comment by Etsija** [comment]
I'm also doing my best to `git bisect` the problem, but the local dev environment seems to be now broken in a way that I cannot.

![Screenshot from 2024-12-18 10-32-32](https://github.com/user-attachments/assets/4a88c7d6-22fb-4557-8dfc-88c4c6cdf83f)

So Keycloak health check is failing (the problem I told you about yesterday) -> I cannot log into the Server UI to check for log download when bisecting.

**Comment by mnonnenmacher** [comment]
> @mnonnenmacher can you actually reproduce the issue on your infrastructure? Because like @Etsija said, this is not limited to the Compose setup for us.

No, but we haven't updated for about two weeks for other reasons. So if it was a recent change we would not be affected by it yet.

> So Keycloak health check is failing (the problem I told you about yesterday) -> I cannot log into the Server UI to check for log download when bisecting.

If you go back to before the commit that upgraded Keycloak or that fixed the health check, this is bound to happen. However, I just checked and in Compose none of the Loki config variables are set for the `core` module, so I would be surprised if it ever worked. I'm currently looking into adding the config.

**Comment by mnonnenmacher** [comment]
> This is what I was able to extract from core logs:
> 
> [Explore-logs-2024-12-18 07_52_58.txt](https://github.com/user-attachments/files/18175741/Explore-logs-2024-12-18.07_52_58.txt)

In the log file it looks like some requests fail and some work, or do all requests fail for you in your cloud environment?

**Comment by Etsija** [comment]
> > @mnonnenmacher can you actually reproduce the issue on your infrastructure? Because like @Etsija said, this is not limited to the Compose setup for us.
> 
> No, but we haven't updated for about two weeks for other reasons. So if it was a recent change we would not be affected by it yet.
> 
> > So Keycloak health check is failing (the problem I told you about yesterday) -> I cannot log into the Server UI to check for log download when bisecting.
> 
> If you go back to before the commit that upgraded Keycloak or that fixed the health check, this is bound to happen. However, I just checked and in Compose none of the Loki config variables are set for the `core` module, so I would be surprised if it ever worked. I'm currently looking into adding the config.

OK that probably explains why in my _modified_ environment Keycloak health check _sometimes_ work, sometimes not, but in an unmodified ORT Server clone, it always fails and I cannot even log in: in my modified environment, the `docker-compose.yaml` has these lines added to core module (as per @mmurto):
```
      LOG_FILE_PROVIDER_NAME: loki
      LOKI_SERVER_URL: "https://383a4457-f9cf-4471-a6c4-8b33d9962902.logs.cockpit.nl-ams.scw.cloud"
      LOKI_NAMESPACE: "ort-server"
      LOKI_QUERY_LIMIT: "1000"
      LOKI_PASSWORD: <omitted>

```
So, with these additions, it has worked for local dev environment (but lately, something like every fifth `docker compose up` passes a health check), but now with a "clean" clone of ORT Server, it never works: Keycloak health check always fails, and no login possible.

**Comment by Etsija** [comment]
> > This is what I was able to extract from core logs:
> > [Explore-logs-2024-12-18 07_52_58.txt](https://github.com/user-attachments/files/18175741/Explore-logs-2024-12-18.07_52_58.txt)
> 
> In the log file it looks like some requests fail and some work, or do all requests fail for you in your cloud environment?

If by "all requests" you mean whether it generally works, then yes. Only log file download fails, but everything else (like for example downloading reports) are working.

**Comment by mnonnenmacher** [comment]
> > > This is what I was able to extract from core logs:
> > > [Explore-logs-2024-12-18 07_52_58.txt](https://github.com/user-attachments/files/18175741/Explore-logs-2024-12-18.07_52_58.txt)
> > 
> > 
> > In the log file it looks like some requests fail and some work, or do all requests fail for you in your cloud environment?
> 
> If by "all requests" you mean whether it generally works, then yes. Only log file download fails, but everything else (like for example downloading reports) are working.

No, I actually meant if only some log downloads fail or all of them.

**Comment by Etsija** [comment]
Well it's difficult to check every single run & log, isn't it? So far every download attempt has been failing.

**Comment by mnonnenmacher** [comment]
> Well it's difficult to check every single run & log, isn't it? So far every download attempt has been failing consistently, across multiple products, repositories and runs.

Sure, I think that's good enough 🙂

> but now with a "clean" clone of ORT Server, it never works: Keycloak health check always fails, and no login possible.

I cannot reproduce this, I just updated my repo and did `docker compose pull` and `docker compose up -d` and it just works. Please run the health check script manually inside the Keycloak container and try to figure out why it is failing.

**Comment by Etsija** [comment]
Can you provide me with instructions for that? It's a Java script, and I don't know enough of running it inside the container. I do know how to start a shell inside, but that's it, basically.

BTW, we checked our ScaleWay deployments from this week, and it seems that the only suspicious PR deployed was the Keycloak docker tag upgrade, which was deployed to our infra couple of hours after I've been lastly able to download any logs from the server.

**Comment by Etsija** [comment]
Let me just assure you: I did exactly as you, and
![Screenshot from 2024-12-18 12-02-55](https://github.com/user-attachments/assets/31b268ca-ad34-40c1-87ee-e9e1a392b9ef)

**Comment by mnonnenmacher** [comment]
> Can you provide me with instructions for that? It's a Java script, and I don't know enough of running it inside the container. I do know how to start a shell inside, but that's it, basically.

```
docker exec -it ort-server-keycloak-1 /bin/bash
java /opt/keycloak_init/HealthCheck.java
echo $?
```

If the `java` call does not print any errors but `echo $?` returns `1` instead of `0`, you need to modify the script at `scripts/docker/keycloak/HealthCheck.java` to add some log output and run it again. For example, you could add a line like this before the `System.exit` call to get the exact response code:

```java
System.out.println("responseCode=" + responseCode);
```

> BTW, we checked our ScaleWay deployments from this week, and it seems that the only suspicious PR deployed was the Keycloak docker tag upgrade, which was deployed to our infra couple of hours after I've been lastly able to download any logs from the server.

But that upgrade only affects the Compose environment, not they Keycloak you are running in your cloud.

**Comment by mmurto** [comment]
The [Docker build is broken](https://github.com/eclipse-apoapsis/ort-server/actions/workflows/docker-build.yml?query=branch%3Amain), so there's a drift between checked out / deployed commit and what images are actually deployed. It could make sense to fix that first, as then we at least know what is deployed.

**Comment by mnonnenmacher** [comment]
@Etsija The latest Docker build was successful again, could you try with this one?

**Comment by Etsija** [comment]
@mnonnenmacher sadly, all log downloading still failing on our infra, which was updated yesterday after your PR got merged, so should have newest server images.

**Comment by Etsija** [comment]
Debugging the Keycloak unhealthy problem can't be done, as executing the bach inside the keycloak container exits from the shell/container after a few seconds.

**Comment by Etsija** [comment]
I managed to run the health check inside Keycloak container once, however, most ot the time the bash shell just kicks me out of the shell a few seconds after going in. This error I got once:
```
bash-5.1$ java /opt/keycloak_init/HealthCheck.java 
Exception in thread "main" java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:280)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:386)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:408)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1319)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1252)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1138)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1067)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1690)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1614)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:531)
	at HealthCheck.main(HealthCheck.java:5)
```

**Comment by sschuberth** [comment]
> most ot the time the bash shell just kicks me out of the shell a few seconds after going in.

That's probably because the wrong port is being used. Not that @mnonnenmacher's [fix](https://github.com/eclipse-apoapsis/ort-server/pull/1644/files#diff-52f5ecbc7cd3a0a7fb09a10a01275c6f33efd8ca4ce7ecce92a594da4de8eb92R4) also changes the port from 8080 to 9000. So depending on whether you test a commit that has this fix or not, you might get a "Connection refused".

So actually, you need to bisect on a custom history that "backports" the fix to directly after the Keycloak upgrade, so that any bisect interval has the fix.

**Comment by mnonnenmacher** [comment]
@Etsija I'm confused now about what you are actually debugging. So on the one hand there is the Docker Compose file as it is in the repository. For this log downloads do not work anyway, because `core` is missing the Loki configuration. I started a branch to fix this but this requires some other changes as well. On the other hand there are log downloads failing in your infra, but I don't understand how debugging this can depend on the Keycloak instance started by Compose.

**Comment by sschuberth** [comment]
> On the other hand there are log downloads failing in your infra, but I don't understand how debugging this can depend on the Keycloak instance started by Compose.

IIUC, @Etsija did you some custom Loki setup in combination with the local Docker Compose setup in order to debug the issue locally, although usually log downloads to not work locally.

BTW, by now we saw as a root cause a 401 permission issue when downloading the logs, probably due to a token timeout specific to our infrastructure.

**Comment by sschuberth** [comment]
With https://github.com/eclipse-apoapsis/ort-server/pull/1690 log download in Compose was fixed. While we (Double Open) do still see issues with downloading logs in our production server, this is probably something specific to our deployment, so I'm closing this.
