### ISSUE TITLE
'VCS information is missing from ORT run' when creating a trivial run with minimal config

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#236]
We have earlier been able to successfully create and execute ORT runs with this minimal job configuration:
![Capture](https://github.com/eclipse-apoapsis/ort-server/assets/599904/498dc2b6-8a61-4737-b20f-0a577a32077b)

Lately however these runs immediately after creation cause an error in the logs:
```
ort-server-reporter-worker-1   | 2024-05-17 04:01:43.056 [pool-1-thread-4] level=ERROR o.e.a.o.w.reporter.ReporterWorker - Error while processing message with traceId '54914ce7-4fb6-4dfe-8aad-63cca18a5012': VCS information is missing from ORT run '21'.
ort-server-reporter-worker-1   | 2024-05-17 04:01:43.056 [pool-1-thread-4] level=ERROR o.e.a.o.w.reporter.ReporterComponent - Reporter job '6' failed.
ort-server-reporter-worker-1   | java.lang.IllegalArgumentException: VCS information is missing from ORT run '21'.
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.workers.common.OrtRunService$getOrtRepositoryInformation$1.invoke(OrtRunService.kt:198)
ort-server-orchestrator-1      | 2024-05-17 04:01:42.018 [pool-1-thread-5] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ queue: 'reporter_queue'
ort-server-orchestrator-1      | 2024-05-17 04:01:43.097 [pool-1-thread-6] level=INFO  o.e.a.o.orchestrator.EntrypointKt - Received 'ReporterWorkerError' message. TraceID: '54914ce7-4fb6-4dfe-8aad-63cca18a5012'.
ort-server-orchestrator-1      | 2024-05-17 04:01:43.097 [pool-1-thread-6] level=INFO  o.e.a.o.orchestrator.Orchestrator - Job 6 for endpoint 'reporter' completed in status 'FAILED'.
ort-server-orchestrator-1      | 2024-05-17 04:01:43.103 [pool-1-thread-6] level=INFO  o.e.a.o.orchestrator.Orchestrator - Handling a completed job for endpoint 'reporter' and ORT run 21.
ort-server-orchestrator-1      | 2024-05-17 04:04:17.554 [pool-1-thread-7] level=INFO  o.e.a.o.orchestrator.EntrypointKt - Received 'AnalyzerWorkerResult' message. TraceID: '54914ce7-4fb6-4dfe-8aad-63cca18a5012'.
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.workers.common.OrtRunService$getOrtRepositoryInformation$1.invoke(OrtRunService.kt:188)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt$blockingQueryCatching$1$1.invoke(Database.kt:156)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt$blockingQueryCatching$1$1.invoke(Database.kt:156)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:324)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:371)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:370)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:279)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:379)
ort-server-reporter-worker-1   | 	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:249)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt.blockingQueryCatching(Database.kt:156)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt.blockingQuery(Database.kt:144)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.dao.DatabaseKt.blockingQuery$default(Database.kt:139)
ort-server-reporter-worker-1   | 	at org.eclipse.apoapsis.ortserver.workers.common.OrtRunService.getOrtRepositoryInformation(OrtRunService.kt:188)
```
and the Reporter job fails immediately.

However, the Analyzer starts running and runs without issues. The resulting `jobs` structure from the run is
```{
  "analyzer": {
    "id": 9,
    "createdAt": "2024-05-08T07:37:24Z",
    "startedAt": "2024-05-08T07:37:25Z",
    "finishedAt": "2024-05-08T07:39:56Z",
    "configuration": {
      "allowDynamicVersions": true,
      "packageCurationProviders": [],
      "skipExcluded": true
    },
    "status": "FINISHED"
  },
  "reporter": {
    "id": 4,
    "createdAt": "2024-05-08T07:37:24Z",
    "startedAt": "2024-05-08T07:37:25Z",
    "finishedAt": "2024-05-08T07:37:25Z",
    "configuration": {
      "formats": [
        "ortresult",
        "WebApp"
      ],
      "packageConfigurationProviders": [],
      "assetFiles": [],
      "assetDirectories": []
    },
    "status": "FAILED",
    "reportFilenames": []
  }
}
```
and the run itself is set to FAILED.

**Comment by Etsija** [comment]
This is happening in Docker Compose environment.

**Comment by sschuberth** [comment]
Could this be a side-effect of 34709e07704f695463577e5aef9f6531eeebdad4, @oheger-bosch?

**Comment by oheger-bosch** [comment]
I would rather assume that this is caused by the refactoring of Orchestrator.

I do not fully get: Does the Reporter worker runs immediately or does it wait for the Analyzer to complete?

**Comment by Etsija** [comment]
Strangely enough, it runs (and fails) immediately, unlike before.

**Comment by Etsija** [comment]
I can do another run and provide the full logs if needed.

**Comment by Etsija** [comment]
Some information to help in debugging this:
- runs on May 6 were successful
- runs from May 8 onwards are all failing the Reporter very early (even before Analyzer job has started)

**Comment by oheger-bosch** [comment]
There is indeed a bug in the scheduler algorithm. #270 should hopefully fix this.

**Comment by Etsija** [comment]
Good news you've found the bug! Let me test this tomorrow with a test run and close the issue once verified the fix works.
