### ISSUE TITLE
Creating an ORT run with minimal request body leads to a crash

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#79]
Creating an ORT run for an existing repository (with [this Github URL](https://github.com/doubleopen-project/dos.git)) with request body
```
{
  "revision": "main",
  "jobConfigs": {}
}
```
leads to a crash:
```
ort-server-orchestrator-1      | 2024-04-12 07:51:04.670 [pool-1-thread-4] level=INFO  o.e.a.o.transport.MessagePublisher - Sending 'ConfigRequest' message to 'ConfigEndpoint'. TraceID: 'f83ebfc6-c670-448c-b9a8-458b8dc35c6a'.
ort-server-orchestrator-1      | 2024-04-12 07:51:04.671 [pool-1-thread-4] level=INFO  o.e.a.o.t.MessageSenderFactory - Creating a MessageSender of type 'kubernetes' for endpoint 'config'.
ort-server-orchestrator-1      | 2024-04-12 07:51:04.679 [pool-1-thread-4] level=WARN  o.e.a.o.t.k.KubernetesSenderConfig - Found invalid variables for annotations: []
ort-server-orchestrator-1      | 2024-04-12 07:51:04.679 [pool-1-thread-4] level=WARN  o.e.a.o.t.k.KubernetesSenderConfig - Make sure that these variables are defined and have the format 'key=value'.
ort-server-orchestrator-1      | 2024-04-12 07:51:05.087 [pool-1-thread-4] level=ERROR o.e.a.o.t.r.RabbitMqMessageReceiverFactory - Error during message processing.
ort-server-orchestrator-1      | io.kubernetes.client.openapi.ApiException: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
ort-server-orchestrator-1      |        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:888)
ort-server-orchestrator-1      |        at io.kubernetes.client.openapi.apis.BatchV1Api.createNamespacedJobWithHttpInfo(BatchV1Api.java:592)
ort-server-orchestrator-1      |        at io.kubernetes.client.openapi.apis.BatchV1Api.createNamespacedJob(BatchV1Api.java:536)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.transport.kubernetes.KubernetesMessageSender.send(KubernetesMessageSender.kt:140)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.transport.MessagePublisher.publish(MessagePublisher.kt:88)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.publish(Orchestrator.kt:628)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.scheduleConfigWorkerJob(Orchestrator.kt:543)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.access$scheduleConfigWorkerJob(Orchestrator.kt:96)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator$handleCreateOrtRun$1$2.invoke(Orchestrator.kt:131)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator$handleCreateOrtRun$1$2.invoke(Orchestrator.kt:131)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.scheduleCreatedJobs(Orchestrator.kt:530)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.Orchestrator.handleCreateOrtRun(Orchestrator.kt:133)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.OrchestratorComponent$endpointHandler$1.invoke(Entrypoint.kt:85)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.orchestrator.OrchestratorComponent$endpointHandler$1.invoke(Entrypoint.kt:79)
ort-server-orchestrator-1      |        at org.eclipse.apoapsis.ortserver.transport.rabbitmq.RabbitMqMessageReceiverFactory$createConsumer$1.handleDelivery(RabbitMqMessageReceiverFactory.kt:125)
ort-server-orchestrator-1      |        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
ort-server-orchestrator-1      |        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
ort-server-orchestrator-1      |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ort-server-orchestrator-1      |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ort-server-orchestrator-1      |        at java.base/java.lang.Thread.run(Thread.java:840)
ort-server-orchestrator-1      | Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:8080
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
ort-server-orchestrator-1      |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
ort-server-orchestrator-1      |        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
ort-server-orchestrator-1      |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
ort-server-orchestrator-1      |        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
ort-server-orchestrator-1      |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
ort-server-orchestrator-1      |        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
ort-server-orchestrator-1      |        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
ort-server-orchestrator-1      |        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:884)
ort-server-orchestrator-1      |        ... 19 common frames omitted
ort-server-orchestrator-1      | Caused by: java.net.ConnectException: Connection refused
ort-server-orchestrator-1      |        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
ort-server-orchestrator-1      |        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
ort-server-orchestrator-1      |        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:547)
ort-server-orchestrator-1      |        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
ort-server-orchestrator-1      |        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
ort-server-orchestrator-1      |        at java.base/java.net.Socket.connect(Socket.java:633)
ort-server-orchestrator-1      |        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
ort-server-orchestrator-1      |        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
```
This might be a bug, or then we lack some information as to what the "minimal configuration" of an ORT run is. We get no response from the API, though, as we do when sending other erroneous requests.

**Comment by mmurto** [comment]
It seems that it's trying to create a Kubernetes job, which fails due to not running on Kubernetes.

I went through the configuration, and apparently there's a `CONFIG_SENDER_TRANSPORT_TYPE` which isn't configured in the `docker-compose.yml`. I wonder if this is something that was added after the Docker Compose setup has last been in a working state.

https://github.com/eclipse-apoapsis/ort-server/blob/b95db42a03e666905daf6d978c7a4bf43c77f990/orchestrator/src/main/resources/application.conf#L71-L76

**Comment by Etsija** [comment]
Following @mmurto 's comment, I tried to add this to `docker-compose.yml`:
```
CONFIG_SENDER_TRANSPORT_TYPE: rabbitMQ
CONFIG_SENDER_TRANSPORT_SERVER_URI: "amqp://rabbitmq:5672"
CONFIG_SENDER_TRANSPORT_USERNAME: admin
CONFIG_SENDER_TRANSPORT_PASSWORD: admin
```

It got me a bit further, as the ORT Run changed its status from CREATED to ACTIVE:
![Capture](https://github.com/eclipse-apoapsis/ort-server/assets/599904/d993dd18-6339-4f00-a555-e1d59a183387)

However bumped now into a different problem, which I couldn't find the reason for after some digging:
```
ort-server-orchestrator-1      | 2024-04-17 07:21:56.245 [pool-1-thread-4] level=INFO  o.e.a.o.transport.MessagePublisher - Sending 'ConfigRequest' message to 'ConfigEndpoint'. TraceID: '19f8d349-d37d-4aa2-aed6-2857977a9cfc'.
ort-server-orchestrator-1      | 2024-04-17 07:21:56.246 [pool-1-thread-4] level=INFO  o.e.a.o.t.MessageSenderFactory - Creating a MessageSender of type 'rabbitMQ' for endpoint 'config'.
ort-server-orchestrator-1      | 2024-04-17 07:21:56.248 [pool-1-thread-4] level=INFO  o.e.a.o.c.s.f.ConfigSecretFileProviderFactory - Creating ConfigSecretFileProvider, reading secrets from these files: [/etc/fileBasedSecretStorage/.env.development].
ort-server-orchestrator-1      | 2024-04-17 07:21:56.250 [pool-1-thread-4] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - Creating RabbitMQ sender for endpoint 'config'.
ort-server-orchestrator-1      | 2024-04-17 07:21:56.251 [pool-1-thread-4] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ server URI: 'amqp://rabbitmq:5672'
ort-server-orchestrator-1      | 2024-04-17 07:21:56.251 [pool-1-thread-4] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ user: 'admin'
ort-server-orchestrator-1      | 2024-04-17 07:21:56.251 [pool-1-thread-4] level=INFO  o.e.a.o.t.r.RabbitMqMessageSenderFactory - RabbitMQ queue: 'analyzer_queue'
ort-server-analyzer-worker-1   | 2024-04-17 07:21:56.344 [pool-1-thread-4] level=ERROR o.e.a.o.t.r.RabbitMqMessageReceiverFactory - Error during message processing.
ort-server-analyzer-worker-1   | kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'ortRunId' at path: $
ort-server-analyzer-worker-1   | Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
ort-server-analyzer-worker-1   | JSON input: {"ortRunId":5}
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:598)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.AbstractJsonLexer.failOnUnknownKey(AbstractJsonLexer.kt:593)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.StreamingJsonDecoder.handleUnknown(StreamingJsonDecoder.kt:257)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:243)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:178)
ort-server-analyzer-worker-1   |        at org.eclipse.apoapsis.ortserver.model.orchestrator.AnalyzerRequest$$serializer.deserialize(AnalyzerRequest.kt:27)
ort-server-analyzer-worker-1   |        at org.eclipse.apoapsis.ortserver.model.orchestrator.AnalyzerRequest$$serializer.deserialize(AnalyzerRequest.kt:27)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
ort-server-analyzer-worker-1   |        at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
ort-server-analyzer-worker-1   |        at org.eclipse.apoapsis.ortserver.transport.json.JsonSerializer$Companion$forClass$1.fromJson(JsonSerializer.kt:52)
ort-server-analyzer-worker-1   |        at org.eclipse.apoapsis.ortserver.transport.rabbitmq.RabbitMqMessageConverter.toTransportMessage(RabbitMqMessageConverter.kt:67)
ort-server-analyzer-worker-1   |        at org.eclipse.apoapsis.ortserver.transport.rabbitmq.RabbitMqMessageReceiverFactory$createConsumer$1.handleDelivery(RabbitMqMessageReceiverFactory.kt:116)
ort-server-analyzer-worker-1   |        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
ort-server-analyzer-worker-1   |        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:111)
ort-server-analyzer-worker-1   |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
ort-server-analyzer-worker-1   |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
ort-server-analyzer-worker-1   |        at java.base/java.lang.Thread.run(Thread.java:840)
```

I suspect that docker compose is missing the correct queue name to which to send, or then there's another reason why the `analyzer_queue` gets confused, as we certainly are not sending `ortRunId` when creating the ORT run.

**Comment by mmurto** [comment]
My guess is that it should add the payload to a config queue, not the analyzer queue. Looks like analyzer worker received it from the queue and throws and error due to the payload not being wrong.

Which led to me noticing that the current Docker Compose file doesn't even include the [config worker](https://github.com/eclipse-apoapsis/ort-server/tree/9c96a53f934e995c79638c58e26b088a2cb8fc47/workers/config), which probably is the one that should be watching the config queue. The next steps in fixing this should probably be:

1. Add `config-worker` service to the `docker-compose.yml` and configure the environment variables based on [config worker's application.conf](https://github.com/eclipse-apoapsis/ort-server/blob/9c96a53f934e995c79638c58e26b088a2cb8fc47/workers/config/src/main/resources/application.conf).
2. Add `config_queue` to be created in the Docker Compose RabbitMQ in [here](https://github.com/eclipse-apoapsis/ort-server/blob/9c96a53f934e995c79638c58e26b088a2cb8fc47/scripts/docker/rabbitmq/load_definition.json).

This could get us in the right direction, @Etsija.

**Comment by mnonnenmacher** [comment]
@Etsija @mmurto FYI, I'm almost done with fixing the Docker Compose setup. I'm in meetings the whole morning, but you can expect a PR in the afternoon.

**Comment by Etsija** [comment]
Thanks a lot, @mnonnenmacher.  I actually managed to create and finish an ORT run (with empty configuration) successfully this morning. It only ran the Analyzer, which I suspect is because we sent an empty configuration JSON object to it, but it returned a FINISHED status, which is seen in the server logs as well as in our UI!

If needed, I can document what I did, if it is of any help.

**Comment by Etsija** [comment]
[This commit](https://github.com/eclipse-apoapsis/ort-server/commit/6596fcf9d6af435ebcef2b09e89be3ac8ace0dfd) summarizes the changes I made to create and finish successfully an ORT run in the local docker compose environment. It is given here as a reference, in case it helps someone (although, it will probably include some errors...).
