### ISSUE TITLE
All tests and integration tests failing constantly

### ISSUE THREAD

**Issue by Etsija** [eclipse-apoapsis/ort-server#849]
Related to #720, now even rerunning tests and integration tests actions several times, they fail for PRs not having changes to any back-end code.
```
org.eclipse.apoapsis.ortserver.clients.keycloak.DefaultKeycloakClientTest > SpecInstantiationException STARTED

org.eclipse.apoapsis.ortserver.clients.keycloak.DefaultKeycloakClientTest > SpecInstantiationException FAILED
    java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/
```

**Comment by Etsija** [comment]
Can't reproduce.
